project:
  type: default
  output-dir: _site
  render:
    - main.qmd

lightbox: true

format:
  revealjs:
    # html-math-method: mathjax
    theme:
      - simple
      - elements/title.scss
    transition: slide
    slide-number: true
    incremental: false
    center: true
    navigation-mode: linear
    hash: true
    preview-links: auto
    html-math-method: katex
    css: elements/styles.css
    code-fold: true
  

    

    # Title slide background (ONLY the title slide)
    title-slide-attributes:
      data-background-image: elements/title-page-image.jpg
      data-background-size: contain
      data-background-position: center
      data-background-repeat: no-repeat
      data-background-opacity: "0.9"
