project:
  type: default
  output-dir: _site
  render:
    - main.qmd

format:
  revealjs:
    theme: [simple, elements/title.scss]
    transition: slide
    slide-number: true
    incremental: true

    center: true
    navigation-mode: linear
    hash: true
    preview-links: auto

    html-math-method: katex

    title-slide-attributes:
      data-background-image: elements/title-page-image.jpg
      data-background-size: cover
      data-background-position: center
      data-background-repeat: no-repeat
