project:
  type: default
  output-dir: _site
  render:
    - main.qmd

format:
  revealjs:
    theme:
      - simple
      - elements/title.scss
    transition: slide
    slide-number: true
    incremental: true
    center: true
    navigation-mode: linear
    hash: true
    preview-links: auto
    html-math-method: katex
    css: elements/styles.css

    # Title slide background (ONLY the title slide)
    title-slide-attributes:
      data-background-image: elements/title-page-image.jpg
      data-background-size: contain
      data-background-position: center
      data-background-repeat: no-repeat
      data-background-opacity: "0.9"

